In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df = pd.read_csv('AirplaneAccident.csv')
df.head(4)

Severity  ...  Accident_ID
0                Minor_Damage_And_Injuries  ...         7570
1                Minor_Damage_And_Injuries  ...        12128
2        Significant_Damage_And_Fatalities  ...         2181
3  Significant_Damage_And_Serious_Injuries  ...         5946

[4 rows x 12 columns]

In [ ]:
df = df.drop(['Accident_ID'] , axis=1) # Axis 1 specifies coloumn

In [ ]:
y = df.iloc[: , 0].values

In [ ]:
X = df.iloc[: , 1:].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
df['Severity'].unique()

array(['Minor_Damage_And_Injuries', 'Significant_Damage_And_Fatalities',
       'Significant_Damage_And_Serious_Injuries',
       'Highly_Fatal_And_Damaging'], dtype=object)

In [ ]:
print(y[0:5])
print(df['Severity'])

[1 1 2 3 2]
0                     Minor_Damage_And_Injuries
1                     Minor_Damage_And_Injuries
2             Significant_Damage_And_Fatalities
3       Significant_Damage_And_Serious_Injuries
4             Significant_Damage_And_Fatalities
                         ...                   
9995    Significant_Damage_And_Serious_Injuries
9996                  Highly_Fatal_And_Damaging
9997    Significant_Damage_And_Serious_Injuries
9998                  Minor_Damage_And_Injuries
9999                  Highly_Fatal_And_Damaging
Name: Severity, Length: 10000, dtype: object


In [ ]:
print(y[9995:10000])

[3 0 3 1 0]


In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 ,random_state = 0 )

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy' , random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
y_predictions = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report , confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
print(confusion_matrix(y_test,y_predictions))
print(classification_report(y_test,y_predictions))

[[697  22  13  22]
 [ 20 583  10  14]
 [ 17  12 382   6]
 [ 16  24   4 658]]
              precision    recall  f1-score   support

           0       0.93      0.92      0.93       754
           1       0.91      0.93      0.92       627
           2       0.93      0.92      0.92       417
           3       0.94      0.94      0.94       702

    accuracy                           0.93      2500
   macro avg       0.93      0.93      0.93      2500
weighted avg       0.93      0.93      0.93      2500



In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfr = RandomForestClassifier(criterion = 'entropy' , random_state=0)
rfr.fit(X_train , y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
predictions_rfr = rfr.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,(predictions_rfr)))
print(classification_report(y_test,predictions_rfr))

[[706  23  15  10]
 [ 19 582  14  12]
 [  5  22 382   8]
 [ 26  20   3 653]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.94       754
           1       0.90      0.93      0.91       627
           2       0.92      0.92      0.92       417
           3       0.96      0.93      0.94       702

    accuracy                           0.93      2500
   macro avg       0.93      0.93      0.93      2500
weighted avg       0.93      0.93      0.93      2500



In [ ]:
from sklearn.metrics import accuracy_score
def get_accuracy(max_leaf_nodes , X_train , y_train , X_test , y_test):
  dtree = RandomForestClassifier(max_leaf_nodes=max_leaf_nodes , random_state=0)
  dtree.fit(X_train , y_train)
  preds = dtree.predict(X_test)
  score = accuracy_score(y_test , preds)
  return score

In [ ]:
leaf_nodes_list = [100 , 150 ,200 , 250 , 300 , 350 , 400 ,450 , 500]
accuracy = []
for leafs in leaf_nodes_list:
  auc = get_accuracy(leafs,X_train,y_train,X_test,y_test)
  accuracy.append(auc)

bestleaf = leaf_nodes_list[accuracy.index(max(accuracy))]
print(accuracy)
print(bestleaf)

[0.8488, 0.8656, 0.8812, 0.8856, 0.8872, 0.8916, 0.896, 0.9028, 0.9056]
500


In [ ]:
final_model = DecisionTreeClassifier(max_leaf_nodes=150 , criterion = 'entropy' , random_state = 0)

In [ ]:
final_model.fit(X,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=150,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
import pickle

In [ ]:
Pkl_Filename = "Pickle_RL_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(final_model, file)

In [ ]:
X

array([[4.92237443e+01, 1.40000000e+01, 2.20000000e+01, ...,
        3.13354768e+04, 3.00000000e+00, 4.24352083e-01],
       [6.24657534e+01, 1.00000000e+01, 2.70000000e+01, ...,
        2.60247111e+04, 2.00000000e+00, 3.52349973e-01],
       [6.30593607e+01, 1.30000000e+01, 1.60000000e+01, ...,
        3.92690539e+04, 3.00000000e+00, 3.36390700e-03],
       ...,
       [2.78538813e+01, 1.70000000e+01, 1.00000000e+00, ...,
        3.37719963e+04, 3.00000000e+00, 1.68173043e-01],
       [5.62100457e+01, 8.00000000e+00, 0.00000000e+00, ...,
        3.98204192e+04, 2.00000000e+00, 2.63809290e-02],
       [5.00000000e+01, 1.30000000e+01, 3.00000000e+00, ...,
        2.60053230e+04, 2.00000000e+00, 1.70358910e-02]])

In [ ]:
X[0]

array([4.92237443e+01, 1.40000000e+01, 2.20000000e+01, 7.12853236e+01,
       2.72117562e-01, 7.80400000e+01, 2.00000000e+00, 3.13354768e+04,
       3.00000000e+00, 4.24352083e-01])